/* Generated by Together */

package depths.pedagogicalModule.instructionalPlanner;

public class FragmentInfo {
  public FragmentInfo(String curC,String curU){
    currConceptID=curC;
    currUnitID=curU;
  }
  public String getCurrConceptID(){
    return currConceptID;
  }

  public void setCurrConceptID(String currConceptID){
      this.currConceptID= currConceptID;
    }

  public String getCurrUnitID(){
    return currUnitID;
  }

  public void setCurrUnitID(String currUnitID){
      this.currUnitID= currUnitID;
    }

  public String getFragmentID(){
    return fragmentID;
  }

  public void setFragmentID(String fragmentID){
      this.fragmentID= fragmentID;
    }

  public int getDetailLevel(){
    return fragmentDetailLevel;
  }

  public void setDetailLevel(int detailLevel){
      this.fragmentDetailLevel= detailLevel;
    }
    public void setFragmentType(String type){
      this.fragmentType=type;
    }
    public String getFragmentType(){
      return this.fragmentType;
    }
    public void setFragmentProgrammingLanguage(String pl){
      if (pl.equals("")){
        pl="any";
      }

      this.fragmentProgrammingLanguage=pl;
    }
    public String getFragmentProgrammingLanguage(){
      return this.fragmentProgrammingLanguage;
    }

  private String currConceptID;
  private String currUnitID;
  private String fragmentID;
  private int fragmentDetailLevel;
  private String fragmentType;
  private String fragmentProgrammingLanguage;
}
