/* Generated by Together */

package depths.pedagogicalModule.instructionalPlanner;

public class QuestionInfo {
  public QuestionInfo(String concId,String Id,int group,int diffL,String relatedTo){
    this.setConceptID(concId);
    this.setID(Id);
    this.setGroup(group);
    this.setDifficultyLevel(diffL);
    this.setRealtedTo(relatedTo);

  }
  public int getGroup(){
    return group;
  }

  public void setGroup(int group){
      this.group= group;
    }

  public String getRealtedTo(){
    return realtedTo;
  }

  public void setRealtedTo(String realtedTo){
      this.realtedTo= realtedTo;
    }

  public String getID(){
    return ID;
  }

  public void setID(String ID){
      this.ID= ID;
    }

  public int getDifficultyLevel(){
    return difficultyLevel;
  }

  public void setDifficultyLevel(int difficultyLevel){
      this.difficultyLevel= difficultyLevel;
    }

  public String getConceptID(){
    return conceptID;
  }

  public void setConceptID(String conceptID){
      this.conceptID= conceptID;
    }

  private int group;
  private String realtedTo;
  private String ID;
  private int difficultyLevel;
  private String conceptID;
}
