// CodeThatHint STANDARD
// Version: 1.1.0 (30.06.2005)
// Script is FREE for non commercial use.
// Copyright (c) 2003-2005 by CodeThat.Com
// http://www.codethat.com/

var CT_Hnt={};function CT_Hint(w,h,fv,y,x,html,bgc,bgi,css,brd,scr,z){var t=this;t._w=pI(w);t._h=pI(h);t._fv=fv;t._t=y;t._l=x;t._bgc=bgc;t._bgi=bgi;t._css=css;t._brd=brd;t._scr=scr;t._z=z;t._html=html||'';t._hhnt=null;t._hc=null;t._id=CodeThat.newID();t._vis=0;CT_Hnt[t._id]=t};var CHp=CT_Hint.prototype;CHp.create=function(){var t=this,i,brd=t._brd,dw=ua.oldOpera?1:0;var bw,bc,bi,blw,btw,brw;var ch;if(t._hhnt)
return;CT_createLayer(t._id,t._w,t._h,t._t,t._l,1,t._vis,'','','','','','','',t._z,'','',CT_lrSource(t._id+'inn',t._w+dw,t._h,0,0,1,1,'',t._bgc,t._bgi,'',!ua.nn4&&t._scr?'auto':'','','','','','','<div id="'+t._id+'inn2" class="'+t._css+'">'+t._html+'</div>'));if(Undef(t._brd))t._brd={width:1};bw=brd.width=pI(brd.width);bc=brd.color;bi=brd.bgimg;brd.t=brd.t||{};brd.b=brd.b||{};brd.r=brd.r||{};brd.l=brd.l||{};for(i in brd){if(i.length!=1)continue;var b=brd[i];b.w=pI(b.width)||bw;b.color=b.color||bc;b.bgimg=b.bgimg||bi}t._bh=new Array();if(blw=brd.l.w){CT_createLayer(t._id+'l',blw,t._h,t._t,t._l-blw,1,t._vis,'',brd.l.color,brd.l.bgimg,'','','','',t._z,'','','');t._bh.push([CT_el(t._id+'l')[0],0,-blw,'l']);}if(brw=brd.r.w){CT_createLayer(t._id+'r',brw,t._h,t._t,t._l+t._w,1,t._vis,'',brd.r.color,brd.r.bgimg,'','','','',t._z,'','','');t._bh.push([CT_el(t._id+'r')[0],0,t._w,'r']);}if(btw=brd.t.w){CT_createLayer(t._id+'t',t._w+blw+brw,btw,t._t-btw,t._l-blw,1,t._vis,'',brd.t.color,brd.t.bgimg,'','','','',t._z,'','','');t._bh.push([CT_el(t._id+'t')[0],-btw,-blw,'t']);}if(brd.b.w){CT_createLayer(t._id+'b',t._w+blw+brw,brd.b.w,t._t+t._h,t._l-blw,1,t._vis,'',brd.b.color,brd.b.bgimg,'','','','',t._z,'','','');t._bh.push([CT_el(t._id+'b')[0],t._h,-blw,'b']);}if(ua.ie55up){CT_createLayer(t._id+'if',t._w+blw+brw,t._h+btw+brd.b.w,t._t-btw,t._l-blw,1,t._vis,'','','','','','','',t._z-1,'','','<iframe frameborder=0 '+(location.protocol=='https:'?' src="/blank.html"':'')+' style="filter:Alpha(Opacity=0);visibility:inherit;position:absolute;top:0px;left:0px;height:100%;width:100%"></iframe>');t._hif=CT_el(t._id+'if')[0]}t._hhnt=CT_el(t._id)[0];t._hc=CT_el(t._id+'inn')[0];t._hcin=CT_el(t._id+'inn2')[0];
return true};CHp.SRVmove=function(x,y){var t=this;x=pI(x);y=pI(y);if(isNaN(x)||isNaN(y)||y<0)
return;t._t=y;t._l=x;if(t._hhnt){CT_moveTo(t._hhnt,x,y);if(t._hif)CT_moveTo(t._hif,x-t._brd.l.w,y-t._brd.t.w);for(var i=0;i<t._bh.length;i++)CT_moveTo(t._bh[i][0],x+t._bh[i][2],y+t._bh[i][1])}};CHp.SRVchkPos=function(){var t=this,x=t._l,y=t._t;if(t._fv){var wx=CodeThat.getScrollX(),wy=CodeThat.getScrollY();if(x-t._brd.l.w<wx)x=wx+t._brd.l.w;else{var ww=CodeThat.getWinWidth();if(x+t._w+t._brd.r.w>wx+ww)x=wx+ww-t._w-t._brd.r.w;}if(y-t._brd.t.w<wy)y=wy+t._brd.t.w;else{var wh=CodeThat.getWinHeight();if(y+t._h+t._brd.b.w>wy+wh)y=wy+wh-t._h-t._brd.b.w;}}t.SRVmove(x,y);};CHp.vis=function(v){var t=this;t._vis=v;if(t._hhnt){var d=v?'block':'none';CT_vis(t._hhnt,v);CT_display(t._hhnt,d);if(t._hif){CT_vis(t._hif,v);CT_display(t._hif,d)}for(var i=0;i<t._bh.length;i++){CT_vis(t._bh[i][0],v);CT_display(t._bh[i][0],d)}}};CHp.show=function(){var t=this;t.SRVchkPos();t.vis(1);};CHp.hide=function(){this.vis(0);};CHp.getX=function(){
return this._l};CHp.getY=function(){
return this._t};CHp.width=function(){
return this._w};CHp.height=function(){
return this._h};CHp.hidden=function(){
return!this._vis};CodeThat.setOnLoad(function(){CodeThat.loaded=1});