/* Generated by Together */

package depths.presentationModule;

public class Answer {

  public Answer(String ansContent,boolean aTruth){

    this.setContent(ansContent);
    this.setTruth(aTruth);
  }
  public String getContent(){ return content; }

  public void setContent(String content){ this.content = content; }

  public boolean isTruth(){ return truth; }

  public void setTruth(boolean truth){ this.truth = truth; }

  private String content;
  private boolean truth;
}
