/* Generated by Together */

package depths.studentModule;

public class Question {
  public boolean isStudentAnswerTruth(){ return studentAnswerTruth; }

  public void setStudentAnswerTruth(boolean studentAnswerTruth){ this.studentAnswerTruth = studentAnswerTruth; }

  public int getGroup(){ return group; }

  public void setGroup(int group){ this.group = group; }

  public String getID(){ return ID; }

  public void setID(String ID){ this.ID = ID; }

  private boolean studentAnswerTruth;
  private int group;
  private String ID;
}
