/* Generated by Together */

package depths.pedagogicalModule.studentAssessment;

public class FeedbackMechanism {
    /**
     * @link aggregationByValue
     */
    private StatisticalFeedback lnkStatisticalFeedback;

    /**
     * @link aggregationByValue
     */
    private RealtimeFeedback lnkRealtimeFeedback;
}
