/* Generated by Together */

package depths.pedagogicalModule.studentAssessment;

public class RealtimeFeedback {
    private String testDifficultyLevel;
    private int relatedUnit;
    private int testID;
}
