/* Generated by Together */

package depths.pedagogicalModule.studentAssessment;

public class SistemHistoryUpdater {
    private String conceptKnowledgeLevel;
    private String conceptDegreeOfMastery;
    private String testKnowledgeLevel;
    private String testDegreeOfMastery;
    private String currentLessonType;
    private int currentLessonID;
    private int currentConceptID;
}
