/* Generated by Together */

package depths.pedagogicalModule.studentAssessment;

public class StudentModelUpdater {
    /**
     * @link aggregationByValue
     */
    private StudentPerfomanceUpdater lnkStudentPerfomanceUpdater;

    /**
     * @link aggregationByValue
     */
    private SistemHistoryUpdater lnkSistemHistoryUpdater;
}
