/* Generated by Together */

package depths.pedagogicalModule.studentAssessment;

import java.util.Date;

public class StudentPerfomanceUpdater {
    private String learningStyle;
    private Date timeOfLastSession;
    private String detailLevel;
    private String actualSkillLevel;
}
